%% MASSEF
% Multichannel audio source separation evaluation framework.
% 
%% Syntax
% 
%   massef = MASSEF
%   massef = MASSEF(options)
% 
% |massef = MASSEF| instantiates the multichannel audio source separation
% evaluation framework, returning an instance to |massef|. The instance has
% the <help_MASSEF.html#2 properties described below>. Evaluations are
% performed using the <help_MASSEF_evaluate.html evaluate> or
% <help_MASSEF_execute.html execute> methods. See <help_MASSEF.html#3
% methods> below for a list of methods.
% 
% |massef = MASSEF(options)| instantiates MASSEF using the options
% contained in the scalar structure |options|. See <help_MASSEF.html#2
% properties> below for a description of valid fields.
%   
%% Properties
% <html>
% <table>
% <tr>
% <td><tt>blocksize</tt></td>
% <td>When using the parallel computing toolbox, this parameter determines
% the maximum number of <tt>parallel.FevalFuture</tt> objects that are
% considered at any one time. The default is 128.</td>
% </tr>
% <tr>
% <td><tt>creationDate</tt></td>
% <td>Date the object was created (read-only).</td>
% </tr>
% <tr>
% <td><tt>dir</tt></td>
% <td>The MASSEF installation directory (read-only).</td>
% </tr>
% <tr>
% <td><tt>evalPEASS</tt></td>
% <td>A logical value indicating whether PEASS evaluation should be
% executed. The default is <tt>false</tt>.</td>
% </tr>
% <tr>
% <td><tt>evalSTOI</tt></td>
% <td>A logical value indicating whether STOI evaluation should be
% executed. The default is <tt>false</tt>.</td>
% </tr>
% <td><tt>parpool</tt></td>
% <td>A <tt>parallel.Pool</tt> object on which to perform the parallel
% separations. If the parallel computing toolbox is available,
% <tt>MASSEF</tt> will use the current pool by default (as determined
% by <tt>gcp('nocreate')</tt>), if one is open. If the toolbox is not
% available, or no pool is open, separations will be performed
% serially.</td>
% </tr>
% <tr>
% <td><tt>results</tt></td>
% <td>A <a href="help_MASSEFresults.html">MASSEFresults</a> object containing
% results generated by the framework (read-only).</td>
% </tr>
% <tr>
% <td><tt>results_filename</tt></td> <td>The name of the results file
% returned when <a
% href="help_MASSEF_execute.html">MASSEF.execute</a> finishes.
% The default is <tt>'Results/results.mat'</tt>.</td>
% </tr>
% <tr>
% <td><tt>saveDate</tt></td>
% <td>Date the object was last saved (read-only).</td>
% </tr>
% </table>
% </html>
%   
%% Methods
% 
% Methods:
% 
% <html>
% <table>
% <tr>
% <td>MASSEF</td>
% <td>Create an instance of MASSEF.</td>
% </tr>
% <tr>
% <td><a href="help_MASSEF_evaluate.html">evaluate</a></td>
% <td>Run the framework using the input audio files.</td>
% </tr>
% <tr>
% <td><a href="help_MASSEF_execute.html">execute</a></td>
% <td>Run the framework using the input mixtures and separators.</td>
% </tr>
% <tr>
% <td><a href="help_MASSEF_save.html">save</a></td>
% <td>Save the framework's data and results.</td>
% </tr>
% </table>
% </html>
% 
% Static methods:
% 
% <html>
% <table>
% <tr>
% <td><a href="help_MASSEF_doc.html">doc</a></td>
% <td>Display the framework documentation.</td>
% </tr>
% <tr>
% <td><a href="help_MASSEF_install.html">install</a></td>
% <td>Download and install MASSEF dependencies.</td>
% </tr>
% <tr>
% <td><a href="help_MASSEF_start.html">start</a></td>
% <td>Start the framework.</td>
% </tr>
% </table>
% </html>
% 
%% See also
% <help_MASSEFresults.html MASSEFresults>.
% 
% <html>
% <hr>
% <p>Copyright &copy; 2016 <a href="http://www.surrey.ac.uk">University of Surrey</a><br>
% <a href="http://iosr.uk">Institute of Sound Recording, University of Surrey, UK</a></p>
% </html>
